### ISSUE TITLE
Spam in output log

### ISSUE THREAD

**Issue by Clark919** [giltong/LethalCompanyDRP#1]
Spam in output log:
![image](https://github.com/giltong/LethalCompanyDRP/assets/44264851/4f952169-06cf-4c0c-9e9f-1de53b9dd47c)

**Comment by NevanNedall** [comment]
Also experiencing this

**Comment by giltong** [comment]
You gotta give me some more info for this, because I'm getting nothing like it. Are you running discord desktop? Windows? What other mods are you using?
